# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  publishPath: 'publish'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/MyLib/MyLib.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/MyConsoleAppInGitHub/MyConsoleAppInGitHub.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/MyMSTestConsoleApp/MyMSTestConsoleApp.csproj'
    testRunTitle: 'Testing'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/MyConsoleAppInGitHub/MyConsoleAppInGitHub.csproj'
    arguments: '-c $(buildConfiguration) -o $(publishPath)/ --no-build'
    zipAfterPublish: false
    workingDirectory: '**/MyConsoleAppInGitHub'
    # The -c command will tell Azure DevOps to use the buildConfiguration variable. 
    # By default the variable is set to release but you can change it in "Variables" tab on this page
    # The -o argument specifies the location of the published output.
