# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/MyLib/MyLib.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/MyConsoleAppInGitHub/MyConsoleAppInGitHub.csproj'
    arguments: '--configuration Release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/MyMSTestConsoleApp/MyMSTestConsoleApp.csproj'
    testRunTitle: 'Testing'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/MyConsoleAppInGitHub/MyConsoleAppInGitHub.csproj'
    arguments: '--configuration Release'